apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-middleware
  namespace: microservices
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - DNT
      - User-Agent
      - X-Requested-With
      - If-Modified-Since
      - Cache-Control
      - Content-Type
      - Range
      - Authorization
    accessControlExposeHeaders:
      - Content-Length
      - Content-Range
    accessControlAllowCredentials: true
    accessControlAllowOriginList:
      - https://repeaty.posadskiy.com
    accessControlMaxAge: 1728000
    customRequestHeaders:
      X-Forwarded-Proto: https
      X-Real-IP: ""
      X-Forwarded-For: ""
      X-Forwarded-Host: ""

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-middleware
  namespace: microservices
spec:
  rateLimit:
    average: 100
    period: 1s
    burst: 50

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-auth
  namespace: microservices
spec:
  stripPrefix:
    prefixes:
      - /auth

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-user
  namespace: microservices
spec:
  stripPrefix:
    prefixes:
      - /user

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-email
  namespace: microservices
spec:
  stripPrefix:
    prefixes:
      - /email

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-email-template
  namespace: microservices
spec:
  stripPrefix:
    prefixes:
      - /email-template



