apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  MICRONAUT_ENVIRONMENTS: "prod"
  AUTH_DATASOURCE_URL: "jdbc:postgresql://ep-spring-star-ag0jfnwi-pooler.c-2.eu-central-1.aws.neon.tech:5432/auth_db?sslmode=require"
  AUTH_DATABASE_NAME: "auth_db"
  AUTH_DATABASE_USER: "neondb_owner"
  GITHUB_USERNAME: "posadskiy"
  JAEGER_ENDPOINT: "http://jaeger-collector.observability-stack:14268/api/traces"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_PROTOCOL: "smtp"
  EMAIL_AUTH: "true"
  EMAIL_STARTTLS_ENABLE: "true"
  EMAIL_DEBUG: "true" 
