apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
data:
  MICRONAUT_ENVIRONMENTS: "prod"
  DATASOURCE_URL: "jdbc:postgresql://auth-db:5432/auth_db"
  AUTH_DATASOURCE_URL: "jdbc:postgresql://auth-db:5432/auth_db"
  AUTH_DATABASE_NAME: "auth_db"
  AUTH_DATABASE_USER: "kraken"
  GITHUB_USERNAME: "posadskiy"
  JAEGER_ENDPOINT: "http://jaeger-collector.observability-stack:14268/api/traces"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_PROTOCOL: "smtp"
  EMAIL_AUTH: "true"
  EMAIL_STARTTLS_ENABLE: "true"
  EMAIL_DEBUG: "true" 
