apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  DATASOURCE_PASSWORD: "${AUTH_DATABASE_PASSWORD}"
  JWT_GENERATOR_SIGNATURE_SECRET: "${JWT_GENERATOR_SIGNATURE_SECRET}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}" 