apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  AUTH_DATABASE_PASSWORD: "${AUTH_DATABASE_PASSWORD_PROD}"
  JWT_GENERATOR_SIGNATURE_SECRET: "${JWT_GENERATOR_SIGNATURE_SECRET}"
  OAUTH_TOKEN_ENCRYPTION_SECRET_PROD: "${OAUTH_TOKEN_ENCRYPTION_SECRET_PROD}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  GOOGLE_OAUTH_CLIENT_ID: "${GOOGLE_OAUTH_CLIENT_ID}"
  GOOGLE_OAUTH_CLIENT_SECRET: "${GOOGLE_OAUTH_CLIENT_SECRET}"
  FACEBOOK_OAUTH_CLIENT_ID: "${FACEBOOK_OAUTH_CLIENT_ID}"
  FACEBOOK_OAUTH_CLIENT_SECRET: "${FACEBOOK_OAUTH_CLIENT_SECRET}"
  DEV_EMAIL_ADDRESS: "${DEV_EMAIL_ADDRESS}"
  DEV_EMAIL_TOKEN: "${DEV_EMAIL_TOKEN}"
