apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
type: Opaque
stringData:
  DATASOURCE_PASSWORD: "${AUTH_DATABASE_PASSWORD_PROD}"
  JWT_GENERATOR_SIGNATURE_SECRET: "${JWT_GENERATOR_SIGNATURE_SECRET}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  DEV_EMAIL_ADDRESS: "${DEV_EMAIL_ADDRESS}"
  DEV_EMAIL_TOKEN: "${DEV_EMAIL_TOKEN}"
